// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Extraction) DeepCopyInto(out *Extraction) {
	*out = *in
	out.Regex = in.Regex
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Extraction.
func (in *Extraction) DeepCopy() *Extraction {
	if in == nil {
		return nil
	}
	out := new(Extraction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVersion) DeepCopyInto(out *LocalVersion) {
	*out = *in
	out.Extraction = in.Extraction
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVersion.
func (in *LocalVersion) DeepCopy() *LocalVersion {
	if in == nil {
		return nil
	}
	out := new(LocalVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Regex) DeepCopyInto(out *Regex) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Regex.
func (in *Regex) DeepCopy() *Regex {
	if in == nil {
		return nil
	}
	out := new(Regex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteVersion) DeepCopyInto(out *RemoteVersion) {
	*out = *in
	out.Extraction = in.Extraction
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteVersion.
func (in *RemoteVersion) DeepCopy() *RemoteVersion {
	if in == nil {
		return nil
	}
	out := new(RemoteVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resources) DeepCopyInto(out *Resources) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionTracker) DeepCopyInto(out *VersionTracker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionTracker.
func (in *VersionTracker) DeepCopy() *VersionTracker {
	if in == nil {
		return nil
	}
	out := new(VersionTracker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VersionTracker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionTrackerList) DeepCopyInto(out *VersionTrackerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VersionTracker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionTrackerList.
func (in *VersionTrackerList) DeepCopy() *VersionTrackerList {
	if in == nil {
		return nil
	}
	out := new(VersionTrackerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VersionTrackerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionTrackerSpec) DeepCopyInto(out *VersionTrackerSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	out.LocalVersion = in.LocalVersion
	out.RemoteVersion = in.RemoteVersion
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionTrackerSpec.
func (in *VersionTrackerSpec) DeepCopy() *VersionTrackerSpec {
	if in == nil {
		return nil
	}
	out := new(VersionTrackerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionTrackerStatus) DeepCopyInto(out *VersionTrackerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionTrackerStatus.
func (in *VersionTrackerStatus) DeepCopy() *VersionTrackerStatus {
	if in == nil {
		return nil
	}
	out := new(VersionTrackerStatus)
	in.DeepCopyInto(out)
	return out
}
