# This file defines the config for "ct" (chart tester) used by the helm linting GitHub workflow
lint-conf: charts/.ci/lint-config.yaml
check-version-increment: false # Disable checking that the chart version has been bumped
