apiVersion: opvic.skillz.com/v1alpha1
kind: VersionTracker
metadata:
 name: external-dns-app
spec:
  name: external-dns-app
  resources:
    namespaces:
      - cluster-addon-external-dns
    selector:
      matchLabels:
        app.kubernetes.io/name: external-dns
  localVersion:
   strategy: ImageTag
  remoteVersion:
   provider: github
   strategy: releases
   repo: kubernetes-sigs/external-dns
   extraction:
     regex:
       pattern: ^v([0-9]+\.[0-9]+\.[0-9]+)$
       result: $1

