apiVersion: opvic.skillz.com/v1alpha1
kind: VersionTracker
metadata:
 name: cert-manager
spec:
  name: cert-manager
  resources:
    namespaces:
      - cluster-addon-cert-manager
    selector:
      matchLabels:
        app.kubernetes.io/name: cert-manager
  localVersion:
   strategy: ImageTag
  remoteVersion:
   provider: github
   strategy: releases
   repo: jetstack/cert-manager
   extraction:
     regex:
       pattern: ^v([0-9]+\.[0-9]+\.[0-9]+)$
       result: $1

