{{- if and .Values.agent.serviceAccount.create .Values.agent.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "opvic.agent.serviceAccountName" . }}
  labels:
    {{- include "opvic.agent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opvic.skillz.com
  resources:
  - versiontrackers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opvic.skillz.com
  resources:
  - versiontrackers/finalizers
  verbs:
  - update
- apiGroups:
  - opvic.skillz.com
  resources:
  - versiontrackers/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "opvic.agent.serviceAccountName" . }}
  labels:
    {{- include "opvic.agent.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "opvic.agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "opvic.agent.serviceAccountName" . }}
{{- end }}
