{{- if .Values.agent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opvic.fullname" . }}-agent
  labels:
    {{- include "opvic.agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.agent.replicaCount }}
  selector:
    matchLabels:
      {{- include "opvic.agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.agent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opvic.agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opvic.agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      {{- with .Values.agent.initContainers }}
      initContainers: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: agent
          securityContext:
            {{- toYaml .Values.agent.securityContext | nindent 12 }}
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default (cat "v" .Chart.AppVersion | replace " " "") }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          args:
            - "--log.level={{ .Values.agent.log.level }}"
          env:
            - name: AGENT_IDENTIFIER
              value: {{ required "agent.identifier is required" .Values.agent.identifier }}
            - name: AGENT_INTERVAL
              value: {{ .Values.agent.reconcilerInterval }}
            - name: AGENT_TAGS
              value: |
                {{- .Values.agent.tags | nindent 16 }}
            - name: CONTROLPLANE_URL
              value: {{ include "opvic.agent.controlPlaneURL" . }}
            {{- with .Values.agent.extraEnv }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "opvic.sharedAuthSecretName" . }}
            {{- with .Values.agent.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - name: metrics
              containerPort: 8081
              protocol: TCP
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
