{{- if and .Values.agent.serviceAccount.create .Values.agent.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opvic.agent.serviceAccountName" . }}
  labels:
    {{- include "opvic.agent.labels" . | nindent 4 }}
  {{- with .Values.agent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
