{{- if .Values.controlplane.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opvic.fullname" . }}-control-plane
  labels:
    {{- include "opvic.controlplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controlplane.service.type }}
  ports:
    - port: {{ .Values.controlplane.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "opvic.controlplane.selectorLabels" . | nindent 4 }}
{{- end }}
