{{- if .Values.controlplane.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opvic.fullname" . }}-control-plane
  labels:
    {{- include "opvic.controlplane.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controlplane.replicaCount }}
  selector:
    matchLabels:
      {{- include "opvic.controlplane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controlplane.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opvic.controlplane.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opvic.controlplane.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controlplane.podSecurityContext | nindent 8 }}
      {{- with .Values.controlplane.initContainers }}
      initContainers: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: control-plane
          securityContext:
            {{- toYaml .Values.controlplane.securityContext | nindent 12 }}
          image: "{{ .Values.controlplane.image.repository }}:{{ .Values.controlplane.image.tag | default (cat "v" .Chart.AppVersion | replace " " "") }}"
          imagePullPolicy: {{ .Values.controlplane.image.pullPolicy }}
          args:
            - "--log.level={{ .Values.controlplane.log.level }}"
            {{- if .Values.controlplane.log.logHttpRequests }}
            - "--log.http-requests"
            {{- end }}
          env:
            - name: CACHE_EXPIRATION
              value: {{ .Values.controlplane.cache.expiration }}
            - name: CACHE_RECONCILER_INTERVAL
              value: {{ .Values.controlplane.cache.reconcilerInterval }}
            {{- with .Values.controlplane.extraEnv }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "opvic.sharedAuthSecretName" . }}
            {{- if or (.Values.controlplane.providers.github.createSecret) (.Values.controlplane.providers.github.existingSecret) }}
            - secretRef:
                name: {{ include "opvic.controlplane.providers.github.secretName" . }}
            {{- end }}
            {{- with .Values.controlplane.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.controlplane.resources | nindent 12 }}
      {{- with .Values.controlplane.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controlplane.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controlplane.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
