{{- if .Values.controlplane.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opvic.controlplane.serviceAccountName" . }}
  labels:
    {{- include "opvic.controlplane.labels" . | nindent 4 }}
  {{- with .Values.controlplane.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
