
{{- if .Values.controlplane.providers.github.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opvic.controlplane.providers.github.secretName" . }}
  labels:
    {{- include "opvic.controlplane.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.controlplane.providers.github.token }}
  PROVIDER_GITHUB_TOKEN: {{ .Values.controlplane.providers.github.token | quote }}
  {{- else if and (.Values.controlplane.providers.github.appId) (.Values.controlplane.providers.github.appInstallationId) (.Values.controlplane.providers.github.appPrivateKey) }}
  PROVIDER_GITHUB_APP_ID: {{ .Values.controlplane.providers.github.appId | quote }}
  PROVIDER_GITHUB_APP_INSTALLATION_ID: {{ .Values.controlplane.providers.github.appInstallationId | quote }}
  PROVIDER_GITHUB_APP_PRIVATE_KEY: |
    {{- .Values.controlplane.providers.github.appPrivateKey | nindent 4 }}
  {{- else }}
  {{- fail "github provider requires either a token or app secrets to be set" }}
  {{- end }}
{{- end }}
