apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opvic.fullname" . }}-secrets
type: Opaque
data:
  authToken: "{{ .Values.secrets.authToken }}"
  githubToken: "{{ .Values.secrets.githubToken }}"
  githubAppId: "{{ .Values.secrets.githubAppId }}"
  githubAppInstallationId: "{{ .Values.secrets.githubAppInstallationId }}"
  githubAppPrivateKey: "{{ .Values.secrets.githubAppPrivateKey }}"
