{{- if not .Values.sharedAuthentication.existingSecret }}
{{- if or .Values.controlplane.enabled .Values.agent.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opvic.sharedAuthSecretName" . }}
  labels:
    {{- include "opvic.labels" . | nindent 4 }}
type: Opaque
stringData:
  CONTROLPLANE_AUTH_TOKEN: {{ .Values.sharedAuthentication.token | quote }}
{{- end }}
{{- end }}
