{{- $labels := include "opvic.labels" . -}}
{{- range $name, $conf := .Values.versionTrackers }}
---
apiVersion: opvic.skillz.com/v1alpha1
kind: VersionTracker
metadata:
  name: {{ $name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  name: {{ $name }}
  {{- with $conf.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $conf.localVersion }}
  localVersion:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $conf.remoteVersion }}
  remoteVersion:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
