{{- $labels := include "opvic.labels" . -}}
{{- range $vt := .Values.versionTrackers }}
---
apiVersion: opvic.skillz.com/v1alpha1
kind: VersionTracker
metadata:
  name: {{ $vt.name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  name: {{ $vt.name }}
  {{- with $vt.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $vt.localVersion }}
  localVersion:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $vt.remoteVersion }}
  remoteVersion:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
