name: Publish Images

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - "go.mod"
      - "go.sum"
      - 'Dockerfile'
      - 'Dockerfile.agent'
      - '.github/workflows/publish-canary-images.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - "go.mod"
      - "go.sum"
      - 'Dockerfile'
      - 'Dockerfile.agent'
      - '.github/workflows/publish-canary-images.yaml'
  release:
    types: [published]

jobs:
  control-plane:
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        id: version
        uses: haya14busa/action-cond@v1
        with:
          cond: ${{ github.event_name == 'release' }}
          if_true: ${{ github.release.tag_name }}
          if_false: "canary"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: "ghcr.io/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}"
          tags: |
            type=raw,value=${{ steps.version.outputs.value }}
            type=raw,value={{sha}}
            type=ref,event=branch

      - id: date
        run: echo "::set-output name=value::$(date +%FT%TZ)"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ steps.version.outputs.value }}
            REVISION=${{ github.sha }}
            BRANCH=${{ github.ref }}
            BUILD_DATE=${{ steps.date.outputs.value }}
            BUILD_USER=github-actions

  agent:
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        id: version
        uses: haya14busa/action-cond@v1
        with:
          cond: ${{ github.event_name == 'release' }}
          if_true: ${{ github.release.tag_name }}
          if_false: "canary"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: "ghcr.io/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}-agent"
          tags: |
            type=raw,value=${{ steps.version.outputs.value }}
            type=raw,value={{sha}}
            type=ref,event=branch

      - id: date
        run: echo "::set-output name=value::$(date +%FT%TZ)"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.agent
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ steps.version.outputs.value }}
            REVISION=${{ github.sha }}
            BRANCH=${{ github.ref }}
            BUILD_DATE=${{ steps.date.outputs.value }}
            BUILD_USER=github-actions

