name: Publish helm chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/publish-helm-chart.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/publish-helm-chart.yaml'

env:
  KUBE_SCORE_VERSION: 1.10.0
  HELM_VERSION: v3.4.1

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    name: Lint Chart
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Set up kube-score
        run: |
          wget https://github.com/zegl/kube-score/releases/download/v${{ env.KUBE_SCORE_VERSION }}/kube-score_${{ env.KUBE_SCORE_VERSION }}_linux_amd64 -O kube-score
          chmod 755 kube-score

      - name: Kube-score generated manifests
        run: helm template --values charts/opvic/ci/values-kube-score.yaml charts/* | ./kube-score score -
              --ignore-test pod-networkpolicy
              --ignore-test deployment-has-poddisruptionbudget
              --ignore-test deployment-has-host-podantiaffinity
              --ignore-test container-security-context
              --ignore-test pod-probes
              --ignore-test container-image-tag
              --enable-optional-test container-security-context-privileged
              --enable-optional-test container-security-context-readonlyrootfilesystem

      - name: Chart testing
        run: docker run --rm -t -w /repo -v $(pwd):/repo quay.io/helmpack/chart-testing ct lint --all --config charts/.ci/ct-config.yaml

  publish-chart:
  # if not pull request
    if: github.event_name != 'pull_request'
    needs: lint-chart
    runs-on: ubuntu-latest
    name: Publish Chart

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          config: charts/.ci/cr-config.yaml
