name: Release Drafter

on:
  push:
    branches:
      - main
    paths:
      - '!charts/**'
      - '!.github/**'
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
  pull_request_target:
      types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
