name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/workflows/publish-helm-chart.yaml
      - .github/workflows/publish-images.yaml
      - .github/workflows/release-drafter.yaml
      - '**.md'
      - '.gitignore'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: '1.16.x'

    - run: go version
    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install kubebuilder
      run: |
        curl -L -O https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.2/kubebuilder_2.3.2_linux_amd64.tar.gz
        tar zxvf kubebuilder_2.3.2_linux_amd64.tar.gz
        sudo mv kubebuilder_2.3.2_linux_amd64 /usr/local/kubebuilder

    - name: Run tests
      run: make test

    - name: Verify manifests are up-to-date
      run: |
        make manifests
        git diff --exit-code
